// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kR-a44FXL1JrqDgOx8r8avh9_VpdEMY',
    appId: '1:368640739602:web:798c1a9d667c236f2ecbcb',
    messagingSenderId: '368640739602',
    projectId: 'bip-project-france',
    authDomain: 'bip-project-france.firebaseapp.com',
    storageBucket: 'bip-project-france.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgG7guNOarrnzPc_3MqatoqcE-4HLWAM',
    appId: '1:368640739602:android:872aa4b2cba5fe4c2ecbcb',
    messagingSenderId: '368640739602',
    projectId: 'bip-project-france',
    storageBucket: 'bip-project-france.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRyR34YoLDXvJtWuvWxOiArH3nN9ImxI',
    appId: '1:368640739602:ios:e8e97862e861d0772ecbcb',
    messagingSenderId: '368640739602',
    projectId: 'bip-project-france',
    storageBucket: 'bip-project-france.firebasestorage.app',
    iosBundleId: 'com.example.starteu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdRyR34YoLDXvJtWuvWxOiArH3nN9ImxI',
    appId: '1:368640739602:ios:e8e97862e861d0772ecbcb',
    messagingSenderId: '368640739602',
    projectId: 'bip-project-france',
    storageBucket: 'bip-project-france.firebasestorage.app',
    iosBundleId: 'com.example.starteu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1kR-a44FXL1JrqDgOx8r8avh9_VpdEMY',
    appId: '1:368640739602:web:95297b2fa7237a912ecbcb',
    messagingSenderId: '368640739602',
    projectId: 'bip-project-france',
    authDomain: 'bip-project-france.firebaseapp.com',
    storageBucket: 'bip-project-france.firebasestorage.app',
  );
}
